apiVersion: v1
data:
  MONGO_DB: sharkinfo
  MONGO_PASSWORD: Password123
  MONGO_PORT: "27017"
  MONGO_USERNAME: Andrew
kind: ConfigMap
metadata:
  creationTimestamp: null
  labels:
    app: db
  name: db-env
