kind: Deployment
apiVersion: apps/v1
metadata:
  name: nodejs-v1
  labels:
    app: nodejs
    version: v1
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nodejs
      version: v1
  template:
    metadata:
      labels:
        app: nodejs
        version: v1
      annotations:
        sidecar.istio.io/inject: "true"
        sidecar.istio.io/proxyCPULimit: 200m
        sidecar.istio.io/proxyMemoryLimit: 256Mi
        sidecar.istio.io/rewriteAppHTTPProbers: "true"
    spec:
      containers:
      - args:
        - app.js
        env:
        - name: MONGO_DB
          valueFrom:
            configMapKeyRef:
              key: MONGO_DB
              name: nodejs-env
        - name: MONGO_HOSTNAME
          value: db
        - name: MONGO_PASSWORD
          valueFrom:
            configMapKeyRef:
              key: MONGO_PASSWORD
              name: nodejs-env
        - name: MONGO_PORT
          valueFrom:
            configMapKeyRef:
              key: MONGO_PORT
              name: nodejs-env
        - name: MONGO_USERNAME
          valueFrom:
            configMapKeyRef:
              key: MONGO_USERNAME
              name: nodejs-env
        image: registry.us.lmco.com/n3810c/nodejs-app:v6
        name: nodejs
        ports:
        - containerPort: 8080
        resources: {}
      initContainers:
      - name: wait
        image: registry.us.lmco.com/n3810c/busybox
        command: ['sh','-c','until nc -z db:27071; echo waiting for db; sleep 2; done;']
      restartPolicy: Always
status: {}
